addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.13.2")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.2")
addSbtPlugin("org.typelevel" % "sbt-typelevel-ci-release" % "0.5.3")
addSbtPlugin("org.typelevel" % "sbt-typelevel-settings" % "0.5.3")
addSbtPlugin("org.typelevel" % "sbt-typelevel-mergify" % "0.5.3")
addSbtPlugin("com.github.tkawachi" % "sbt-doctest" % "0.10.0")
