addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.13.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.2.0")
addSbtPlugin("org.typelevel" % "sbt-typelevel-ci-release" % "0.4.20")
addSbtPlugin("org.typelevel" % "sbt-typelevel-settings" % "0.4.20")
addSbtPlugin("org.typelevel" % "sbt-typelevel-mergify" % "0.4.20")
addSbtPlugin("com.github.tkawachi" % "sbt-doctest" % "0.10.0")
