import sbt._

/** Generates `ToAnyValueTupleInstances`, the element-wise `ToAnyValue`
  * instances for every tuple arity circe has an `Encoder` for (1 to 22).
  *
  * Every arity needs its own instance: without one, a tuple falls through to
  * circe's tuple `Encoder`, which encodes each element with its `Encoder` and
  * never consults the element's `ToAnyValue`, so a redacting instance would be
  * bypassed.
  */
object ToAnyValueTupleBoilerplate {
  val MaxArity: Int = 22

  def generate(sourceManagedDir: File): Seq[File] = {
    val file = sourceManagedDir / "com" / "dwolla" / "tracing" / "otel4s" / "ToAnyValueTupleInstances.scala"
    IO.write(file, source)
    Seq(file)
  }

  private def instance(arity: Int): String = {
    val indices = 1 to arity
    val typeParams = indices.map(i => s"A$i").mkString(", ")
    val tupleType = s"Tuple$arity[$typeParams]"
    val evidence = indices.map(i => s"a$i: ToAnyValue[A$i]").mkString(", ")
    val elements = indices.map(i => s"a$i.toAnyValue(t._$i)").mkString(", ")

    s"""  implicit def tuple${arity}ToAnyValue[$typeParams](implicit $evidence): ToAnyValue[$tupleType] =
       |    ToAnyValue.instance[$tupleType](t => AnyValue.seq(Seq($elements)))
       |""".stripMargin
  }

  private def source: String =
    s"""// Generated by project/ToAnyValueTupleBoilerplate.scala; do not edit.
       |package com.dwolla.tracing.otel4s
       |
       |import org.typelevel.otel4s.AnyValue
       |
       |/** Element-wise instances for tuples of arity 1 to $MaxArity: a tuple
       |  * records as a sequence of its elements' own encodings, in position, so
       |  * each element's `ToAnyValue` (including a redacting one) is used rather
       |  * than circe's tuple `Encoder`.
       |  *
       |  * The shape matches circe's JSON array for a tuple: an element whose
       |  * encoding is itself a sequence stays nested. That differs from
       |  * `ToAnyValue`'s `ContravariantSemigroupal#product`, which flattens one
       |  * level of sequence to stay associative; reach for `product` (or
       |  * `tupled`) only when that flattening is what you want.
       |  *
       |  * Ranked between `ToAnyValue`'s companion and the `Encoder` fallback in
       |  * `LowPriorityToAnyValueInstances`, so a tuple never reaches the fallback
       |  * while an instance for the tuple type in the companion still wins.
       |  */
       |trait ToAnyValueTupleInstances extends LowPriorityToAnyValueInstances {
       |${(1 to MaxArity).map(instance).mkString("\n")}}
       |""".stripMargin
}
